name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  APP_CHECK_TOKEN_WEBSITE: ${{ secrets.APP_CHECK_TOKEN_WEBSITE }}
  NPM_ACCESS_TOKEN:        ${{ secrets.NPM_ACCESS_TOKEN }}
  NX_CLOUD_ACCESS_TOKEN:   ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - id:   cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key:  node-modules-cache-${{ hashFiles('package-lock.json') }}
      - if:  steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - id:   auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_WEB_AUTHN }}
          token_format:     access_token
      - run: npx nx run website:deploy
        env:
          FIREBASE_TOKEN: ${{ steps.auth.outputs.access_token }}
      - run: npx nx run-many --target build --all
      - run:               npm publish dist/libs/types --access public
        continue-on-error: true
      - run:               npm publish dist/libs/api --access public
        continue-on-error: true
      - run:               npm publish dist/libs/browser --access public
        continue-on-error: true
      - run:               npm publish dist/libs/server --access public
        continue-on-error: true
      - run:               npm publish dist/libs/extension --access public
        continue-on-error: true
