name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-cache-${{ hashFiles('package-lock.json') }}
      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm i @nrwl/nx-linux-x64-gnu@^15
      - run: npx nx run-many --target build --all
        env:
          NX_CLOUD_ACCESS_TOKEN: '${{ secrets.NX_CLOUD_ACCESS_TOKEN }}'
          APP_CHECK_TOKEN_DEMO: '${{ secrets.APP_CHECK_TOKEN_DEMO }}'
      - run: npm publish dist/libs/functions && npm publish dist/libs/browser
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_WEB_AUTHN }}'
          channelId: live
          projectId: fir-web-authn
